# change the followings to match your Github username and repo name
baseurl: "/personal" # the name of your github repo
url: "https:/naikpreet.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Naikpreet M"
description: Full-Stack Web Developer

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Naikpreet M
author-bio: Full-Stack Developer  # change to false to hide
author-image: Me.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
# - text: About
#   permalink: about
# - text: Blog
#   permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/naikpreet
linkedin: https://linkedin.com/in/naikpreet-m-422237140/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "| Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
